# Generated by Django 4.2.1 on 2023-05-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRSTAY_APP', '0003_user_registration_rooms_user_registration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='owner_name',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
