# Generated by Django 4.2.1 on 2023-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRSTAY_APP', '0006_remove_user_registration_property_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='Rooms',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
