# Generated by Django 4.2.1 on 2023-05-20 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QRSTAY_APP', '0007_alter_user_registration_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=240, null=True)),
                ('qr_url', models.CharField(max_length=240, null=True)),
                ('qr_code', models.CharField(max_length=240, null=True)),
                ('status', models.CharField(max_length=240, null=True)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QRSTAY_APP.user_registration')),
            ],
        ),
    ]
