# Generated by Django 4.2.1 on 2023-05-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRSTAY_APP', '0008_room_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_qr',
            name='qr_code',
            field=models.FileField(max_length=240, null=True, upload_to=''),
        ),
    ]
