# Generated by Django 4.2.1 on 2023-05-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRSTAY_APP', '0009_alter_room_qr_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_qr',
            name='qr_file_status',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
